<?php
/**
 * Implementation of hook_views_api().
 */
function jmapping_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'jmapping'),
  );
}

/**
 * Implementation of template preprocess for the view fields
 */
function template_preprocess_views_jmapping_view_jmappingrows(&$vars) {
  $view = $vars['view'];
  $options = $vars['options'];
  $data = array();
  $vars['fields'] = array(); // ensure it's at least an empty array.
  foreach ($view->field as $id => $field) {
    $field_output = $view->field[$id]->theme($vars['row']);
    $object = array();
    $object['content'] = $field_output;

    // find the option (ie title, description, slide, thumbnail)  for the field
    foreach ($options as $field_title => $field_label) {
      if ($field_label == $id) {
        $object['option'] = $field_title;
      }
    }
    // This is to check if the field has an option. If not ignore.
    if (count($object) > 1 ) {
      $vars['fields'][$object['option']]->content = $object['content'];
      if ($object['option'] == 'title_field') {
        $vars['fields']['title_field']->content = check_markup($vars['fields']['title_field']->content, $format_id = 'full_html', '', $check = FALSE);
        $vars['fields']['title_field']->stripped = trim(strip_tags($vars['fields']['title_field']->content));
      }
      if ($object['option'] == 'address_field') {
        $vars['fields']['address_field']->content = check_markup($vars['fields']['address_field']->content, $format_id = 'full_html', '', $check = FALSE);
      }
      if ($object['option'] == 'lat_field') {
        $data['lat'] = trim(strip_tags($vars['fields']['lat_field']->content));
      }
      if ($object['option'] == 'lng_field') {
        $data['lng'] = trim(strip_tags($vars['fields']['lng_field']->content));
      }
      if ($object['option'] == 'nid_field') {
        $data['nid'] = trim(strip_tags($vars['fields']['nid_field']->content));
      }
    }
  }
  $metadata = array();
  if (!empty($data['nid']) || !empty($data['lng']) || !empty($data['lat'])){
    $metadata = array(
      'id' => $data['nid'],
      'point' => array(
        'lng' => $data['lng'],
        'lat' => $data['lat'],
      ),
    );
  }
  $vars['fields']['metadata']->content = json_encode($metadata);
}